### ISSUE TITLE
Unable to install vpc-infrastructure ibm-cloud plugin on s390x

### ISSUE THREAD

**Issue by bfabec** [IBM-Cloud/ibm-cloud-cli-release#176]
Unable to install plugin vpc-infrastructure on s390x/Ubuntu. Could you please forward to the vpc-infrastructure team?

```
ibmcloud plugin install vpc-infrastructure
Looking up 'vpc-infrastructure' from repository 'IBM Cloud'...
FAILED
Could not find compatible binary to install for plug-in vpc-infrastructure[infrastructure-service].
```

**Comment by steveclay** [comment]
From looking at the configuration of the plug-in repository, it looks like there should be a binary for this platform. Could you try one or two other plug-ins as a test? `dl-cli` and `schematics` also have a version for s390. Also, please include what version of the CLI you are using (2.1.1?) and for the failure, a trace would also be helpful. You can enable trace with `ibmcloud config --trace true` . Thank you

**Comment by bfabec** [comment]
Thanks @steveclay for helping!

The install of schematics works:
```
ibmcloud plugin install schematics
Looking up 'schematics' from repository 'IBM Cloud'...
Plug-in 'schematics 1.6.1' found in repository 'IBM Cloud'
Attempting to download the binary file...
 16.41 MiB / 16.41 MiB [=======================================================================================================================================================================================] 100.00% 2s
17206264 bytes downloaded
Installing binary...
OK
Plug-in 'schematics 1.6.1' was successfully installed into /root/.bluemix/plugins/schematics. Use 'ibmcloud plugin show schematics' to show its details.
```

But dl-cli has the same problem:
```
root@tivlp48:~# ibmcloud config --trace true
root@tivlp48:~# ibmcloud plugin install dl-cli
Looking up 'dl-cli' from repository 'IBM Cloud'...

REQUEST: [2021-11-02T16:24:38Z]
GET /ibm-cloud-cli-plugin-metadata/bluemix-repo-index.yml HTTP/1.1
Host: download.clis.cloud.ibm.com
Accept: application/json
Accept-Language: en-US
Accept-Language: en
Content-Type: application/json
User-Agent: IBM Cloud CLI 2.1.1 / linux



RESPONSE: [2021-11-02T16:24:38Z] Elapsed: 707ms
HTTP/1.1 200 OK
Content-Length: 610409
Accept-Ranges: bytes
Connection: keep-alive
Content-Type: binary/octet-stream
Date: Tue, 02 Nov 2021 16:24:38 GMT
Etag: "f0797a9113adfdf61ab6edda50fbf82c"
Last-Modified: Mon, 01 Nov 2021 17:15:57 GMT
Server: Cleversafe
X-Amz-Request-Id: 13cc20c1-8f5b-46c0-96f6-fb03cf8367f2
X-Clv-Request-Id: 13cc20c1-8f5b-46c0-96f6-fb03cf8367f2
X-Clv-S3-Version: 2.5


[SKIP BINARY OCTET-STREAM CONTENT]
FAILED
Could not find compatible binary to install for plug-in dl-cli.
```

And the cloud trace for vpc-infrastructure:
```
ibmcloud plugin install vpc-infrastructure
Looking up 'vpc-infrastructure' from repository 'IBM Cloud'...

REQUEST: [2021-11-02T16:25:31Z]
GET /ibm-cloud-cli-plugin-metadata/bluemix-repo-index.yml HTTP/1.1
Host: download.clis.cloud.ibm.com
Accept: application/json
Accept-Language: en-US
Accept-Language: en
Content-Type: application/json
User-Agent: IBM Cloud CLI 2.1.1 / linux



RESPONSE: [2021-11-02T16:25:32Z] Elapsed: 515ms
HTTP/1.1 200 OK
Content-Length: 610409
Accept-Ranges: bytes
Connection: keep-alive
Content-Type: binary/octet-stream
Date: Tue, 02 Nov 2021 16:25:32 GMT
Etag: "f0797a9113adfdf61ab6edda50fbf82c"
Last-Modified: Mon, 01 Nov 2021 17:15:57 GMT
Server: Cleversafe
X-Amz-Request-Id: 1d4ffe6d-5400-40df-a506-2566cba74d18
X-Clv-Request-Id: 1d4ffe6d-5400-40df-a506-2566cba74d18
X-Clv-S3-Version: 2.5


[SKIP BINARY OCTET-STREAM CONTENT]
FAILED
Could not find compatible binary to install for plug-in vpc-infrastructure[infrastructure-service].
```

**Comment by bfabec** [comment]
Looking at the yml response (https://download.clis.cloud.ibm.com/ibm-cloud-cli-plugin-metadata/bluemix-repo-index.yml), I don't see a s390x for vpc-infrastructure, but see one for schematics:
```
name: vpc-infrastructure
  description: Manage Virtual Private Cloud infrastructure service
  aliases:
  - infrastructure-service
  created: 2019-05-29
  updated: 2021-10-11
  company: IBM
  versions:
  - version: 0.5.8
    updated: 2019-11-07
    binaries:
    - platform: win32
      url: https://plugins.cloud.ibm.com/downloads/bluemix-plugins/vpc-infrastructure/0.5.8/vpc-infrastructure-windows-386-0.5.8.exe
      checksum: 887bd522eb30dc1560fc397c5cfeadeb65a107c2
      sha256_checksum: 0b06234fea6095c3958612f63e16055c55ea39d4484fd8d2cfbd32809bf7c168
    - platform: win64
      url: https://plugins.cloud.ibm.com/downloads/bluemix-plugins/vpc-infrastructure/0.5.8/vpc-infrastructure-windows-amd64-0.5.8.exe
      checksum: 4e0796bbc5ee79c14cf54e05b3838b783fb5cfc9
      sha256_checksum: 52cc76ba39e3b5adb248025bb3a21134f9ff11f77f82cd38bba1de69dcac7839
    - platform: linux32
      url: https://plugins.cloud.ibm.com/downloads/bluemix-plugins/vpc-infrastructure/0.5.8/vpc-infrastructure-linux-386-0.5.8
      checksum: 049f88d944efc57b7a82c6c7e065e5a4a7520482
      sha256_checksum: a536f1936f08940e62db1f17db4d3062492b6343a300723c89ed3b566bfa1c8b
    - platform: linux64
      url: https://plugins.cloud.ibm.com/downloads/bluemix-plugins/vpc-infrastructure/0.5.8/vpc-infrastructure-linux-amd64-0.5.8
      checksum: cbba96e499684f85b5b7d69e61fb42ce1f197100
      sha256_checksum: a1fa015aceadb66810b133aae798e37d70ceba40c732eb988c473471853604d1
    - platform: osx
      url: https://plugins.cloud.ibm.com/downloads/bluemix-plugins/vpc-infrastructure/0.5.8/vpc-infrastructure-darwin-amd64-0.5.8
      checksum: a4dc41cf278b0dfb3e424c73925bcecf76a12d45
      sha256_checksum: ab53c0d3de6596ee62c502d976dc554b0d24aba21fcce3e282cb4a18d9a371c0
    - platform: ppc64le
      url: https://plugins.cloud.ibm.com/downloads/bluemix-plugins/vpc-infrastructure/0.5.8/vpc-infrastructure-linux-ppc64le-0.5.8
      checksum: 61480bd44aa4d0801b879841e0da708f7c19e1c4
      sha256_checksum: 094d4805bc1c0f0b2d56d643a1fdda22983ece0aba52ef58b63c021fa569f1e6
```
