### ISSUE TITLE
multiple manifest ibmcloud fn deploy

### ISSUE THREAD

**Issue by neiesc** [IBM-Cloud/ibm-cloud-cli-release#198]
I'm can multiple manifest to organaze my functions:
`package.yml`
```
packages:
  procjet-production:
    version: 1.0
    license: Apache-2.0
```

`function-production.yml`
```
actions:
  function-production:
    function: dist/function.bundle.js
    runtime: nodejs
    limits:
      memorySize: 192
```

`manifest.yml`
```
include:
  - manifests/package.yml
  - manifests/function-production.yml
```

and run:
`ibmcloud fn deploy -m manifest.yml`

I got the follow error:
```
==> yaml: unmarshal errors:
==> line 1: field include not found in type parsers.YAML
```
